spring:
  application:
    name: spring-kotlin-web
server:
  port: 9001

# actuator config
management:
  endpoints:
    enabled-by-default: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 10042
